services:
  front-app:
    container_name: frontend-dev
    pull_policy: build
    build:
      context: ../frontend-next-app
      target: development
    ports:
      - 3000:3000
    environment:
      - TOKEN=${TOKEN}
      - CMS_URL=http://cms:1337
    volumes:
      - ${DEV_SRC_CODE}:/app
    depends_on:
      - cms
  cms:
    container_name: starostwo-cms-dev
    pull_policy: build
    build:
      context: ../../CMS-app
      dockerfile: Dockerfile.dev
    ports:
      - 1337:1337
    env_file:
      - .env
    volumes:
      - ${STRAPI_DEV_DB_DIR_PATH}:/opt/app/.tmp/
