services:
  front-app:
    container_name: frontend-prod
    pull_policy: build
    build:
      context: ../frontend-next-app
      target: production
    ports:
      - 80:3000
    env_file:
      - .env
    depends_on:
      - cms
  cms:
    container_name: cms-prod
    pull_policy: build
    build:
      context: ../../CMS-app
      dockerfile: Dockerfile.prod
    ports:
      - 1337:1337
    env_file:
      - .env
    volumes:
      - ${STRAPI_PROD_DB_DIR_PATH}:/opt/app/.tmp
